### ISSUE TITLE
Requested value 'modal_dfc'/'adventure'/'art_series' was not found.

### ISSUE THREAD

**Issue by isalfati** [jdharmon/scryfallapi-csharp#1]
Hello!

When using getNamed method to fetch the new modal_dfc cards from using your csharp api an exception is thrown.

Just letting you know. If it has nothing to do with your API, disregad this issue.

Thank you.

----------
Microsoft.Rest.SerializationException
  HResult=0x80131500
  Message=Unable to deserialize the response.
  Source=BreakingZapBot
  StackTrace:
   at Scryfall.API.Cards.<GetNamedWithHttpMessagesAsync>d__6.MoveNext() in C:\Users\ivans\Desktop\BreakingZapBot\Scryfall\Cards.cs:line 402
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Scryfall.API.CardsExtensions.<GetNamedAsync>d__3.MoveNext() in C:\Users\ivans\Desktop\BreakingZapBot\Scryfall\CardsExtensions.cs:line 116
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Scryfall.API.CardsExtensions.GetNamed(ICards operations, String exact, String fuzzy, String set, String format, String face, String version, Nullable`1 pretty) in C:\Users\ivans\Desktop\BreakingZapBot\Scryfall\CardsExtensions.cs:line 91
   at BreakingZapBot.CardManager.FetchCard(String aCardName) in C:\Users\ivans\Desktop\BreakingZapBot\CardManager.cs:line 29
   at BreakingZap.Program.<Bot_OnMessageReceived>d__4.MoveNext() in C:\Users\ivans\Desktop\BreakingZapBot\Program.cs:line 74

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
JsonSerializationException: Error converting value "modal_dfc" to type 'System.Nullable`1[Scryfall.API.Models.Layouts]'. Path 'layout', line 1, position 428.

Inner Exception 2:
ArgumentException: Requested value 'modal_dfc' was not found.

**Comment by isalfati** [comment]
Hi again!

Quick update: Cards with layouts "Adventures" and "art_series" can't be fetched either.

**Comment by isalfati** [comment]
Closing this topic.

How did I solve it? I just edited configuration files (adding missing card types) and regenerated all the API.
